### ISSUE TITLE
Add exit node support

### ISSUE THREAD

**Issue by edgar-vincent** [cosmic-utils/gui-scale-applet#3]
Hello!

Thank you very much for writing this, it is a very useful applet.

Do you think adding support for exit nodes would be doable?

Thanks again!

EV

**Comment by bhh32** [comment]
Yes, I think it could be do-able. I had planned on possibly doing it, so I’ll put it on the roadmap. I’m currently working on implementing the Tail Drop feature, so I’ll put exit-nodes as the next feature to work on.

**Comment by edgar-vincent** [comment]
Brilliant! Thanks a lot!

**Comment by bhh32** [comment]
# Feature To-Do List
## Logic
- [ ] Add logic to make the current host an exit node
- [ ] Add logic to have an exit node allow LAN access, if the current host is an exit node
- [ ] Add logic to get available exit nodes
- [ ] Add logic to get suggested exit node
- [ ] Add logic to get selected exit node, if one is being used

## UI
- [ ] Add a toggle to make the current host an exit node
- [ ] Add a toggle to allow LAN access if the current host is an exit node
- [ ] Add a combo box that lists available exit nodes
- [ ] Add an UI element, either a notification, status, or some other mechanism, to let the user know which available exit node is the suggested one
- [ ] Add an UI element of some sort to let the user know what exit node is currently selected

## UI Logic
To-Do

## Model Struct Fields that Need Added
- [ ] is_exit_node: bool
- [ ] allow_lan: bool
- [ ] avail_exit_nodes: Vec<String>
- [ ] sel_exit_node: String
- [ ] sug_exit_node: String

## Messages to Tie Logic and UI Together
- [ ] UpdateIsExitNode
- [ ] AllowLanAccess
- [ ] UpdateAvailExitNodes
- [ ] UpdateSelExitNode
- [ ] UpdateSugExitNode

**Comment by bhh32** [comment]
> Brilliant! Thanks a lot!

This feature is almost completed. You can try out what I currently have by clinging the repo and checking out the exit node dev branch. Hopefully, it'll be complete by the end of the week.

**Comment by bhh32** [comment]
Feature is complete and merge into the main branch.

**Comment by edgar-vincent** [comment]
Thanks a lot and sorry for not having replied to your previous comment. I use NixOS, which doesn't make it easy for me to build the applet, but I'm working on it.

4 Nov 2024 07:29:25 Bryan Hyland ***@***.***>:
