### ISSUE TITLE
Applet present in settings but not showing up in the top panel

### ISSUE THREAD

**Issue by NahsiN** [cosmic-utils/gui-scale-applet#9]
Hello, I am using pop_os 22.04. I followed the installation instructions:
1. `sudo tailscale set --operator=$USER` before installing the deb file.
2.  Download and install the deb file (1.0.0)
I can see the GUI-Scale-Applet scale applet show up in the Configure Panel Applets section of the setting but it doesn't show up in my top panel. 

Configure Panel Applets section 
![screenshot-2024-10-30-12-48-27](https://github.com/user-attachments/assets/91eb3b4e-2edc-4d3f-b89f-2e19772b9754)

End Segment of Panel.
![screenshot-2024-10-30-12-49-24](https://github.com/user-attachments/assets/6cedddd7-52e1-44ee-a00f-1a693beda98d)

**Comment by bhh32** [comment]
@NahsiN, I just want you to know that this bug has been fixed, but not release yet. It will be released after the last little bits of the exit node feature are complete. I'm very close to finishing that feature set; I'm hoping by the end of next week. I'll keep this open until I've pushed the fix to the main branch.

**Comment by bhh32** [comment]
@NahsiN, this bug fix is complete. I just have to package it and update the release.

**Comment by bhh32** [comment]
This bug has been fixed and tested. It has been pushed to the main branch and packaged as a .deb and .rpm (Fedora 40 and Fedora 41). Closing issue.
